import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface NewsTemplate {
  title: string;
  summary: string;
  content: string;
  category: string;
  sector: string;
  entities: string[];
  region: string;
  sentiment: "bullish" | "bearish" | "neutral";
  sentiment_score: number;
  confidence: number;
  impact_magnitude: "low" | "medium" | "high" | "severe";
  predicted_stock_move: number;
  affected_sectors: string[];
  affected_companies: string[];
  market_prediction: string;
  gold_impact: number;
  dollar_impact: number;
  rupee_impact: number;
  crypto_impact: number;
  oil_impact: number;
  is_verified: boolean;
  verification_notes: string;
  credibility_score: number;
  key_factors: string[];
  time_horizon: string;
}

const TEMPLATES: NewsTemplate[] = [
  {
    title: "Nifty Hits Fresh Record High as Banking Stocks Rally on Strong Q2 Earnings",
    summary: "The Nifty 50 crossed 25,000 for the first time, driven by a broad-based banking rally after ICICI Bank and SBI reported better-than-expected quarterly earnings.",
    content: "The Nifty 50 index surged to a fresh all-time high of 25,012, crossing the 25,000 mark for the first time, driven by a strong banking sector rally. ICICI Bank gained 3.2% after reporting 18% profit growth, while SBI rose 2.8% on improved asset quality. The broader market saw participation from auto, IT, and metal stocks. Foreign institutional investors pumped in Rs 3,200 crore in the cash segment. Analysts at Motilal Oswal raised their Nifty target to 26,500 for December 2026, citing strong earnings momentum and macro stability. The Bank Nifty outperformed with a 1.8% gain. Market breadth was positive with 1,450 advances against 580 declines.",
    category: "corporate",
    sector: "Banking",
    entities: ["Nifty 50", "ICICI Bank", "SBI", "Motilal Oswal"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 72,
    confidence: 88,
    impact_magnitude: "high",
    predicted_stock_move: 2.5,
    affected_sectors: ["Banking", "NBFC", "Financial Services"],
    affected_companies: ["ICICI Bank", "SBI", "HDFC Bank", "Axis Bank", "Bank Nifty"],
    market_prediction: "Strong banking earnings and record Nifty levels suggest continued bullish momentum. Expect 2-3% upside in banking stocks. FII inflows supporting the rally. Bank Nifty to outperform.",
    gold_impact: -0.3,
    dollar_impact: -0.2,
    rupee_impact: 0.15,
    crypto_impact: 0.5,
    oil_impact: -0.1,
    is_verified: true,
    verification_notes: "Nifty levels verified via NSE real-time data. Earnings figures confirmed from company filings. FII data from NSDL. Broker target confirmed via Motilal Oswal research note.",
    credibility_score: 92,
    key_factors: ["Nifty crosses 25,000 for first time", "ICICI Bank profit up 18%", "SBI asset quality improves", "FII inflow of Rs 3,200 crore", "Motilal Oswal target 26,500"],
    time_horizon: "short-term",
  },
  {
    title: "Sensex Plunges 800 Points as Global Selloff Hits Indian Markets",
    summary: "Heavy selling pressure dragged the Sensex down over 800 points as weak US jobs data and recession fears triggered a global equity selloff.",
    content: "The BSE Sensex plummeted over 800 points to 80,200, while the Nifty fell below 24,500, as a global risk-off wave hit Indian equities. The selloff was triggered by weaker-than-expected US jobs data that raised recession concerns, leading to a sharp decline in US futures and Asian markets. IT stocks were the worst hit with Infosys down 3.5%, TCS falling 2.8%, and Wipro losing 4.1%. The India VIX surged 18% to 16.2, indicating heightened fear in the market. Foreign institutional investors sold Rs 5,800 crore worth of Indian equities. The rupee weakened to 84.15 against the dollar. Gold prices rose 1.2% as investors sought safe haven. Analysts advise caution but note that India's macro fundamentals remain strong.",
    category: "global",
    sector: "IT",
    entities: ["Sensex", "Nifty 50", "Infosys", "TCS", "Wipro", "India VIX"],
    region: "global",
    sentiment: "bearish",
    sentiment_score: -68,
    confidence: 82,
    impact_magnitude: "high",
    predicted_stock_move: -2.8,
    affected_sectors: ["IT", "Banking", "Metals", "Auto"],
    affected_companies: ["Infosys", "TCS", "Wipro", "HCL Tech", "Tech Mahindra"],
    market_prediction: "Global risk-off triggered by US recession fears. Expect 2-4% downside in IT stocks and broad market weakness. India VIX spike indicates fear. Gold to benefit as safe haven. Rupee under pressure.",
    gold_impact: 1.8,
    dollar_impact: 0.8,
    rupee_impact: -0.4,
    crypto_impact: -1.5,
    oil_impact: -2.5,
    is_verified: true,
    verification_notes: "Index levels verified via BSE/NSE real-time data. US jobs data confirmed via Bureau of Labor Statistics. FII data from NSDL. VIX levels from NSE.",
    credibility_score: 90,
    key_factors: ["Sensex down 800+ points", "US jobs data disappoints", "FII sells Rs 5,800 crore", "India VIX up 18%", "Rupee weakens to 84.15"],
    time_horizon: "intraday",
  },
  {
    title: "Reliance Jio Announces 5G Tariff Hike of 15%, Stock Surges 4%",
    summary: "Reliance Jio announced a 15% tariff hike across its 5G plans, effective immediately, sending Reliance Industries shares up 4% on expectations of improved ARPU.",
    content: "Reliance Jio, India's largest telecom operator, announced a 15% increase in its 5G tariff plans effective immediately. The move is expected to improve average revenue per user (ARPU) by Rs 25-30 per month. Reliance Industries shares surged 4% to Rs 3,050 on the news. Analysts at CLSA upgraded the stock to buy with a target of Rs 3,300, citing the tariff hike as a key ARPU driver. Bharti Airtel also gained 2.5% on expectations of a similar hike. The telecom sector has been under pressure due to intense competition, and this hike signals pricing discipline. Jio's 5G subscriber base has crossed 18 crore users. The company expects minimal churn as the plans offer 50% more data. Kotak Institutional Equities estimates a 12% boost to Jio's FY27 revenue from the hike.",
    category: "corporate",
    sector: "Telecom",
    entities: ["Reliance Jio", "Reliance Industries", "Bharti Airtel", "CLSA", "Kotak Equities"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 75,
    confidence: 85,
    impact_magnitude: "medium",
    predicted_stock_move: 3.2,
    affected_sectors: ["Telecom", "Technology"],
    affected_companies: ["Reliance Industries", "Bharti Airtel", "Vodafone Idea"],
    market_prediction: "Tariff hike positive for telecom sector. Reliance to see 3-4% upside. ARPU improvement of Rs 25-30 expected. Bharti Airtel likely to follow with similar hike. Sector re-rating likely.",
    gold_impact: 0,
    dollar_impact: -0.1,
    rupee_impact: 0.1,
    crypto_impact: 0,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "Tariff hike confirmed via Jio official website. Stock price verified via NSE. CLSA upgrade confirmed via broker note. Subscriber data from TRAI.",
    credibility_score: 88,
    key_factors: ["15% 5G tariff hike", "ARPU expected to rise Rs 25-30", "Reliance stock up 4%", "18 crore 5G subscribers", "CLSA target Rs 3,300"],
    time_horizon: "medium-term",
  },
  {
    title: "RBI Intervenes as Rupee Hits Record Low of 84.50 Against Dollar",
    summary: "The Reserve Bank of India intervened in the forex market after the rupee plunged to a record low of 84.50, selling dollars to curb volatility amid global risk aversion.",
    content: "The Indian rupee hit a record low of 84.50 against the US dollar before the Reserve Bank of India stepped in to sell dollars and curb excessive volatility. The rupee had opened weaker at 84.20 and declined steadily as global risk aversion and dollar strength weighed on emerging market currencies. The RBI is estimated to have sold $2-3 billion in the spot market. Forex reserves stand at $684 billion, providing adequate cushion. The 10-year bond yield rose to 7.05%. Analysts at DBS Bank expect the rupee to stabilize around 84-84.50 range. Export-oriented sectors like IT and pharma may benefit from rupee weakness, while import-heavy sectors like oil & gas and electronics face headwinds. The RBI reiterated its commitment to maintaining orderly market conditions.",
    category: "economic",
    sector: "Currency",
    entities: ["RBI", "Indian Rupee", "US Dollar", "DBS Bank"],
    region: "india",
    sentiment: "bearish",
    sentiment_score: -45,
    confidence: 80,
    impact_magnitude: "medium",
    predicted_stock_move: -1.5,
    affected_sectors: ["IT", "Pharmaceuticals", "Oil & Gas", "Electronics"],
    affected_companies: ["Infosys", "TCS", "Sun Pharma", "IOC", "BPCL"],
    market_prediction: "Rupee at record low pressures import-heavy sectors. IT and pharma exporters to benefit. RBI intervention may stabilize around 84-84.50. Bond yields rising. Expect mixed sectoral impact.",
    gold_impact: 1.5,
    dollar_impact: 0.6,
    rupee_impact: -0.5,
    crypto_impact: -0.8,
    oil_impact: 0.8,
    is_verified: true,
    verification_notes: "Rupee level verified via RBI reference rate. RBI intervention confirmed by multiple forex dealers. Bond yield from CCIL. Forex reserves from RBI weekly bulletin.",
    credibility_score: 91,
    key_factors: ["Rupee at record low 84.50", "RBI sold $2-3 billion", "Forex reserves at $684B", "10-year yield at 7.05%", "IT and pharma to benefit"],
    time_horizon: "short-term",
  },
  {
    title: "Brent Crude Spikes 5% After Drone Attack on Saudi Oil Facility",
    summary: "Brent crude oil surged 5% to $78 per barrel after a drone attack on a major Saudi Aramco oil facility raised supply disruption fears in the Middle East.",
    content: "Brent crude oil prices spiked 5% to $78 per barrel after a drone attack targeted a major Saudi Aramco oil processing facility in Abqaiq. While the facility's operations were not significantly disrupted, the attack raised concerns about supply security in the Middle East. WTI crude also rose 4.5% to $74.50. For India, which imports over 85% of its crude oil needs, the price spike is a negative development. OMC stocks like IOC, BPCL, and HPCL saw mixed reactions. Aviation stocks declined with IndiGo down 2.5% on higher fuel cost concerns. Paint companies like Asian Paints and Berger Paints also faced selling pressure. The government may delay fuel price reductions if the spike sustains. Goldman Sachs raised its short-term Brent forecast to $82. OPEC+ announced an emergency meeting to discuss supply response.",
    category: "commodity",
    sector: "Energy",
    entities: ["Brent Crude", "Saudi Aramco", "OPEC+", "Goldman Sachs", "IndiGo"],
    region: "global",
    sentiment: "bearish",
    sentiment_score: -52,
    confidence: 78,
    impact_magnitude: "high",
    predicted_stock_move: -2.2,
    affected_sectors: ["Aviation", "Paints", "OMC", "Auto", "Logistics"],
    affected_companies: ["IndiGo", "Asian Paints", "IOC", "BPCL", "HPCL"],
    market_prediction: "Crude spike negative for oil-importing India. Aviation and paint stocks to decline 2-3%. OMCs face mixed impact. INR may weaken on higher import bill. Expect 1-2% drag on Nifty.",
    gold_impact: 1.2,
    dollar_impact: 0.4,
    rupee_impact: -0.3,
    crypto_impact: 0.3,
    oil_impact: 5.0,
    is_verified: true,
    verification_notes: "Attack confirmed via Saudi government statement. Oil prices verified on ICE and NYMEX. Goldman Sachs forecast confirmed via research note. OPEC+ meeting announced on official website.",
    credibility_score: 89,
    key_factors: ["Brent up 5% to $78", "Drone attack on Aramco facility", "India imports 85% of crude", "IndiGo down 2.5%", "OPEC+ emergency meeting"],
    time_horizon: "short-term",
  },
  {
    title: "TCS Wins $2.5 Billion Multi-Year Contract from European Bank",
    summary: "Tata Consultancy Services secured a $2.5 billion, 10-year IT services contract from a major European bank, its largest-ever deal win.",
    content: "Tata Consultancy Services (TCS) announced a $2.5 billion, 10-year IT services contract from a major European bank, marking the largest deal in the company's history. The contract covers digital transformation, cloud migration, and core banking modernization. TCS shares surged 3.5% on the news, lifting the broader IT sector. The deal is expected to generate $250 million in annual revenue and involve 15,000 employees. CEO K Krithivasan highlighted the deal as a validation of TCS's digital transformation capabilities. The contract margin is expected to be in the 26-28% range, above the company average. Brokerage firm JPMorgan raised TCS to overweight with a target of Rs 4,500. The positive news also lifted Infosys and Wipro by 1.5% and 1.2% respectively. The deal strengthens India's position as a global IT services hub.",
    category: "corporate",
    sector: "IT",
    entities: ["TCS", "K Krithivasan", "JPMorgan", "Infosys", "Wipro"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 80,
    confidence: 87,
    impact_magnitude: "high",
    predicted_stock_move: 3.5,
    affected_sectors: ["IT", "Technology", "BPO"],
    affected_companies: ["TCS", "Infosys", "Wipro", "HCL Tech", "Tech Mahindra"],
    market_prediction: "Largest-ever deal for TCS is a major positive. Expect 3-4% upside in TCS and 1-2% in IT peers. Deal margin of 26-28% above company average. Sector sentiment to improve. JPMorgan upgrade adds conviction.",
    gold_impact: 0,
    dollar_impact: -0.1,
    rupee_impact: 0.2,
    crypto_impact: 0.3,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "Deal confirmed via TCS official press release and exchange filing. Contract value and duration verified. JPMorgan upgrade confirmed via research note. Stock price from NSE.",
    credibility_score: 93,
    key_factors: ["$2.5B largest-ever deal", "10-year contract duration", "$250M annual revenue", "15,000 employees involved", "JPMorgan target Rs 4,500"],
    time_horizon: "long-term",
  },
  {
    title: "Gold Slumps 2% as Dollar Strengthens on Hawkish Fed Comments",
    summary: "Gold prices fell 2% in Indian markets as the US dollar strengthened following hawkish comments from Federal Reserve officials about keeping rates higher for longer.",
    content: "Gold prices declined 2% to Rs 72,800 per 10 grams in Indian markets as the US dollar strengthened on hawkish Federal Reserve commentary. Fed officials indicated that rate cuts may be slower than markets expect, pushing the dollar index up 0.5%. Internationally, gold futures fell to $2,680 per ounce. The weakness in gold comes after a strong rally that saw prices hit record highs. Silver also declined 1.8%. Gold ETFs saw outflows of Rs 150 crore. However, analysts at UBS maintain a bullish long-term outlook with a target of $2,900 per ounce, citing central bank purchases and geopolitical risks. The RBI continues to add gold to its reserves. Jewelry demand is expected to pick up during the festive season, providing support at lower levels.",
    category: "commodity",
    sector: "Precious Metals",
    entities: ["Gold", "Federal Reserve", "UBS", "RBI", "Silver"],
    region: "global",
    sentiment: "bearish",
    sentiment_score: -35,
    confidence: 75,
    impact_magnitude: "medium",
    predicted_stock_move: -1.8,
    affected_sectors: ["Precious Metals", "Jewelry", "Gold ETF"],
    affected_companies: ["Titan", "Rajesh Exports", "SGB", "Nippon Gold ETF"],
    market_prediction: "Gold down 2% on dollar strength and hawkish Fed. Short-term bearish but festive demand may provide support. Titan and jewelry stocks face 1-2% downside. Long-term outlook remains bullish per UBS.",
    gold_impact: -2.0,
    dollar_impact: 0.5,
    rupee_impact: -0.2,
    crypto_impact: -0.5,
    oil_impact: 0.3,
    is_verified: true,
    verification_notes: "Gold prices verified on MCX and COMEX. Fed comments confirmed via FOMC minutes and official speeches. Dollar index from ICE. UBS target confirmed via research note.",
    credibility_score: 88,
    key_factors: ["Gold down 2% to Rs 72,800", "Dollar index up 0.5%", "Fed hawkish on rate cuts", "Gold ETF outflows Rs 150 crore", "UBS long-term target $2,900"],
    time_horizon: "short-term",
  },
  {
    title: "Adani Green Energy Commission 2 GW Solar Project in Rajasthan",
    summary: "Adani Green Energy announced the commissioning of a 2 GW solar power project in Rajasthan, the largest single-site solar facility in India.",
    content: "Adani Green Energy commissioned a 2 gigawatt (GW) solar power project in Jaisalmer, Rajasthan, making it the largest single-site solar facility in India. The project will power 4 million households and reduce carbon emissions by 5 million tonnes annually. The company's total renewable capacity now stands at 15 GW. Adani Green shares rose 3.5% on the announcement. The project was completed 3 months ahead of schedule and at 10% below budget. The company has a target of 45 GW renewable capacity by 2030. Brokerage firm ICICI Securities raised its target to Rs 2,200, citing faster execution and capacity addition. The project has a 25-year power purchase agreement with SECI at Rs 2.55 per unit. This strengthens India's renewable energy push and the company's position as the largest renewable player.",
    category: "corporate",
    sector: "Energy",
    entities: ["Adani Green Energy", "SECI", "ICICI Securities"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 70,
    confidence: 84,
    impact_magnitude: "medium",
    predicted_stock_move: 2.8,
    affected_sectors: ["Renewable Energy", "Solar", "Power"],
    affected_companies: ["Adani Green Energy", "Tata Power", "NTPC", "JSW Energy"],
    market_prediction: "Largest solar project commissioning positive for Adani Green and renewable sector. Expect 3-4% upside in Adani Green. Faster execution and below-budget delivery impressive. ICICI Securities target Rs 2,200.",
    gold_impact: 0,
    dollar_impact: -0.1,
    rupee_impact: 0.1,
    crypto_impact: 0,
    oil_impact: -0.3,
    is_verified: true,
    verification_notes: "Commissioning confirmed via company exchange filing. Capacity data verified with MNRE. PPA terms confirmed via SECI. ICICI Securities target via research note.",
    credibility_score: 90,
    key_factors: ["2 GW largest single-site solar", "Powers 4 million households", "Total capacity at 15 GW", "Completed 3 months early", "Target 45 GW by 2030"],
    time_horizon: "medium-term",
  },
  {
    title: "India CPI Inflation Rises to 5.2% in October, Above RBI Tolerance Band",
    summary: "India's retail inflation accelerated to 5.2% in October, breaching the RBI's 4% +/- 2% tolerance band, driven by surging food prices.",
    content: "India's Consumer Price Index (CPI) inflation rose to 5.2% in October 2025, up from 4.8% in September, breaching the RBI's tolerance band. The spike was primarily driven by food inflation, which accelerated to 9.1% due to surging vegetable and cereal prices. Core inflation remained stable at 3.5%. The higher inflation print complicates the RBI's rate cut timeline, with markets now pricing in a delay until April 2026. Bond yields rose 8 basis points to 7.02%. The rupee weakened marginally. Banking stocks declined on rate cut delay concerns. Finance Ministry officials stated that food inflation is transient and core inflation remains under control. Vegetable prices are expected to cool as winter supply improves. However, analysts at Nomura revised their rate cut forecast from February to April 2026.",
    category: "economic",
    sector: "Economy",
    entities: ["CPI Inflation", "RBI", "Nomura", "Finance Ministry"],
    region: "india",
    sentiment: "bearish",
    sentiment_score: -42,
    confidence: 86,
    impact_magnitude: "medium",
    predicted_stock_move: -1.2,
    affected_sectors: ["Banking", "Auto", "Real Estate", "NBFC"],
    affected_companies: ["HDFC Bank", "SBI", "Bajaj Finance", "Maruti Suzuki", "LIC Housing"],
    market_prediction: "Inflation above RBI tolerance band delays rate cuts. Bond yields to rise. Rate-sensitive sectors like banking, auto, and real estate face 1-2% downside. Rate cut now expected April 2026 instead of February.",
    gold_impact: 0.8,
    dollar_impact: 0.3,
    rupee_impact: -0.2,
    crypto_impact: -0.3,
    oil_impact: 0.2,
    is_verified: true,
    verification_notes: "CPI data officially released by MOSPI. Food inflation breakdown verified. Bond yield from CCIL. Nomura forecast revision confirmed via research note. Finance Ministry comments from official statement.",
    credibility_score: 94,
    key_factors: ["CPI inflation at 5.2%", "Food inflation at 9.1%", "Core inflation stable at 3.5%", "Bond yields up 8bps to 7.02%", "Rate cut delayed to April 2026"],
    time_horizon: "medium-term",
  },
  {
    title: "Bharti Airtel Acquires 25% Stake in Tata Play for Rs 1,200 Crore",
    summary: "Bharti Airtel acquired a 25% stake in Tata Play, India's largest DTH provider, for Rs 1,200 crore, marking a strategic push into the home entertainment segment.",
    content: "Bharti Airtel announced the acquisition of a 25% stake in Tata Play (formerly Tata Sky), India's largest direct-to-home (DTH) television provider, for Rs 1,200 crore. The deal values Tata Play at Rs 4,800 crore. The acquisition gives Bharti Airtel a stronger foothold in the home entertainment segment, complementing its existing Airtel Xstream TV offering. Bharti Airtel shares rose 1.8% on the announcement. The DTH market in India has 65 million subscribers, with Tata Play holding a 33% market share. The deal is expected to create synergies in content delivery and customer acquisition. Tata Play has been facing increasing competition from OTT platforms. Analysts at Morgan Stanley view the deal positively, noting it strengthens Airtel's converged telecom-media-play. The transaction is subject to regulatory approvals and is expected to close by Q4 FY26.",
    category: "corporate",
    sector: "Telecom",
    entities: ["Bharti Airtel", "Tata Play", "Morgan Stanley"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 55,
    confidence: 80,
    impact_magnitude: "low",
    predicted_stock_move: 1.5,
    affected_sectors: ["Telecom", "Media", "Entertainment"],
    affected_companies: ["Bharti Airtel", "Tata Play", "Reliance Jio", "Vodafone Idea"],
    market_prediction: "Strategic acquisition positive for Bharti Airtel. Expect 1-2% upside. Strengthens home entertainment portfolio. Synergies in content delivery likely. DTH market consolidation positive for industry.",
    gold_impact: 0,
    dollar_impact: 0,
    rupee_impact: 0,
    crypto_impact: 0,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "Acquisition confirmed via Bharti Airtel exchange filing. Valuation and stake verified. Morgan Stanley view from research note. Market share data from TRAI.",
    credibility_score: 89,
    key_factors: ["Rs 1,200 crore for 25% stake", "Tata Play valued at Rs 4,800 crore", "33% DTH market share", "65M DTH subscribers in India", "Synergies in content delivery"],
    time_horizon: "medium-term",
  },
  {
    title: "Foreign Investors Pull Out Rs 12,000 Crore from Indian Markets in November",
    summary: "Foreign portfolio investors withdrew Rs 12,000 crore from Indian equities in November so far, the highest monthly outflow in 2025, amid valuation concerns and global headwinds.",
    content: "Foreign portfolio investors (FPIs) have pulled out Rs 12,000 crore from Indian equities in November 2025, marking the highest monthly outflow of the year. The selling has been concentrated in financial services, IT, and auto sectors. The outflows come amid concerns over elevated valuations, with the Nifty trading at 22x forward earnings compared to the 10-year average of 18x. Global factors including US rate uncertainty and China's stimulus-driven market rally have also contributed. Domestic institutional investors (DIIs) have absorbed the selling, pumping in Rs 15,000 crore. The rupee has weakened to 84.30 on FPI outflows. Market participants note that FPI selling may continue if global volatility persists. However, India's strong GDP growth and earnings momentum provide a floor. Analysts at Jefferies note that the FPI-DII divergence is a structural shift, with domestic flows becoming the primary market driver.",
    category: "global",
    sector: "Financial Services",
    entities: ["FPI", "DII", "Nifty 50", "Jefferies"],
    region: "india",
    sentiment: "bearish",
    sentiment_score: -50,
    confidence: 78,
    impact_magnitude: "medium",
    predicted_stock_move: -2.0,
    affected_sectors: ["Banking", "IT", "Auto", "Financial Services"],
    affected_companies: ["HDFC Bank", "ICICI Bank", "Infosys", "Maruti Suzuki", "Bajaj Finance"],
    market_prediction: "FPI outflows of Rs 12,000 crore create selling pressure. Expect 1-3% downside in financials and IT. DII absorption limits damage. Nifty valuations at 22x forward earnings elevated. Rupee under pressure.",
    gold_impact: 0.5,
    dollar_impact: 0.4,
    rupee_impact: -0.3,
    crypto_impact: -0.5,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "FPI data from NSDL custodial data. DII flows from AMFI. Valuation data from Bloomberg. Jefferies view from research note. Rupee level from RBI reference rate.",
    credibility_score: 90,
    key_factors: ["Rs 12,000 crore FPI outflow", "Highest monthly outflow in 2025", "Nifty at 22x forward earnings", "DII inflow of Rs 15,000 crore", "Selling in financials, IT, auto"],
    time_horizon: "short-term",
  },
  {
    title: "Zomato Shares Surge 8% as Food Delivery Business Turns Profitable",
    summary: "Zomato reported its first profitable quarter in the food delivery business, sending shares up 8% as the company's path to sustained profitability becomes clearer.",
    content: "Zomato (now Eternal Ltd) shares surged 8% after the company reported its first profitable quarter in the core food delivery business. Adjusted EBITDA for food delivery turned positive at Rs 65 crore, compared to a loss of Rs 45 crore a year ago. The company's GOUV (gross order value) grew 25% year-on-year, driven by both order frequency and average order value. The Blinkit quick commerce segment also showed improved unit economics, with contribution margin turning positive in 4 cities. Management guided for sustained profitability in food delivery going forward. The company's cash position improved to Rs 12,500 crore. Brokerage firm Goldman Sachs upgraded the stock to buy with a target of Rs 320, citing the profitability milestone. The hypergrowth segment (Blinkit) remains a key value driver, with 100%+ GOUV growth. Analysts note that the food delivery business has reached a scale where profitability is sustainable.",
    category: "corporate",
    sector: "Technology",
    entities: ["Zomato", "Eternal Ltd", "Goldman Sachs", "Blinkit"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 78,
    confidence: 83,
    impact_magnitude: "high",
    predicted_stock_move: 5.5,
    affected_sectors: ["Technology", "Food Delivery", "Quick Commerce"],
    affected_companies: ["Zomato", "Swiggy", "Cloud kitchens"],
    market_prediction: "First profitable quarter is a major milestone for Zomato. Expect 5-8% upside. Food delivery profitability sustainable at scale. Blinkit showing improved economics. Goldman Sachs buy target Rs 320.",
    gold_impact: 0,
    dollar_impact: -0.1,
    rupee_impact: 0.1,
    crypto_impact: 0.5,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "Earnings confirmed via company exchange filing. EBITDA and GOUV figures verified. Goldman Sachs upgrade via research note. Cash position from balance sheet.",
    credibility_score: 91,
    key_factors: ["First profitable quarter for food delivery", "Adjusted EBITDA of Rs 65 crore", "GOUV growth of 25% YoY", "Blinkit contribution margin positive in 4 cities", "Goldman Sachs target Rs 320"],
    time_horizon: "medium-term",
  },
  {
    title: "Modi Government Announces Rs 50,000 Crore Semiconductor Push",
    summary: "Prime Minister Narendra Modi's cabinet approved a Rs 50,000 crore incentive package for semiconductor manufacturing, aiming to make India a global chip hub.",
    content: "The Union Cabinet, chaired by Prime Minister Narendra Modi, approved a Rs 50,000 crore incentive package under the Semicon India program to boost domestic semiconductor manufacturing. The package includes capital subsidies of up to 50%, interest subsidies, and power tariff rebates for semiconductor fabrication units. The government has already received proposals worth Rs 2.5 lakh crore from companies including Tata Electronics, Micron, and CG Power. The Tata Electronics fab in Dholera, Gujarat, with an investment of Rs 91,000 crore, is expected to be operational by 2026. The semiconductor mission aims to create 50,000 jobs and reduce import dependency. The announcement boosted semiconductor-related stocks, with Tata Electronics, CG Power, and Kaynes Semicon gaining. The move positions India as an alternative to China in the global semiconductor supply chain. Analysts at Citi note that the semiconductor push could add 0.5% to India's GDP over 5 years.",
    category: "political",
    sector: "Technology",
    entities: ["Narendra Modi", "Semicon India", "Tata Electronics", "Micron", "CG Power"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 73,
    confidence: 85,
    impact_magnitude: "high",
    predicted_stock_move: 4.0,
    affected_sectors: ["Semiconductors", "Technology", "Electronics", "Manufacturing"],
    affected_companies: ["Tata Electronics", "CG Power", "Kaynes Semicon", "Micron India"],
    market_prediction: "Rs 50,000 crore semiconductor package is a game-changer. Expect 4-6% upside in semiconductor stocks. Tata Electronics fab operational by 2026. India positioned as China alternative. 50,000 jobs and 0.5% GDP boost expected.",
    gold_impact: 0,
    dollar_impact: -0.2,
    rupee_impact: 0.2,
    crypto_impact: 0.5,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "Cabinet approval confirmed via PIB press release. Investment figures verified with MeitY. Tata Electronics fab details from company filing. Citi analysis via research note.",
    credibility_score: 92,
    key_factors: ["Rs 50,000 crore semiconductor package", "50% capital subsidy", "Rs 2.5 lakh crore proposals received", "Tata fab in Dholera by 2026", "50,000 jobs projected"],
    time_horizon: "long-term",
  },
  {
    title: "Bitcoin Crashes 8% as Binance Faces Regulatory Probe in India",
    summary: "Bitcoin tumbled 8% to Rs 58 lakh as reports emerged of a regulatory probe into Binance's operations in India, triggering a broad crypto market selloff.",
    content: "Bitcoin prices crashed 8% to Rs 58 lakh in Indian markets following reports that Indian financial regulators have launched an investigation into Binance's operations. The probe focuses on compliance with FEMA regulations and potential money laundering concerns. The news triggered a broad selloff in the crypto market, with Ethereum down 7%, Solana declining 10%, and major altcoins falling 5-12%. The total crypto market capitalization fell below $2 trillion. Indian crypto exchanges reported a surge in selling pressure. The FIU-IND has reportedly issued a show cause notice to Binance. This follows similar regulatory actions in the US and Europe. Analysts note that regulatory uncertainty could lead to short-term outflows from crypto to gold and other safe-haven assets. However, long-term crypto adoption in India remains strong with 15 crore+ crypto investors.",
    category: "commodity",
    sector: "Cryptocurrency",
    entities: ["Bitcoin", "Binance", "FIU-IND", "Ethereum", "Solana"],
    region: "global",
    sentiment: "bearish",
    sentiment_score: -72,
    confidence: 75,
    impact_magnitude: "high",
    predicted_stock_move: -3.0,
    affected_sectors: ["Cryptocurrency", "Blockchain", "Technology"],
    affected_companies: ["Bitcoin", "Ethereum", "Solana", "Binance"],
    market_prediction: "Binance regulatory probe triggers crypto crash. Expect continued volatility in crypto markets. Bitcoin may test Rs 55 lakh support. Gold to benefit from safe-haven flows. Regulatory overhang to persist short-term.",
    gold_impact: 1.5,
    dollar_impact: 0.3,
    rupee_impact: -0.1,
    crypto_impact: -8.0,
    oil_impact: 0,
    is_verified: false,
    verification_notes: "Regulatory probe reported by multiple sources but not yet officially confirmed by FIU-IND or Binance. Show cause notice details unverified. Crypto price movements confirmed on exchanges. Investors should await official confirmation.",
    credibility_score: 65,
    key_factors: ["Bitcoin down 8% to Rs 58 lakh", "Binance faces regulatory probe", "FIU-IND show cause notice", "Ethereum down 7%, Solana down 10%", "Crypto market cap below $2T"],
    time_horizon: "short-term",
  },
  {
    title: "Hindalco Shares Jump 6% as Aluminum Prices Hit 2-Year High on Supply Crunch",
    summary: "Hindalco surged 6% as aluminum prices reached a 2-year high of $2,650 per tonne on the LME, driven by supply disruptions and robust demand.",
    content: "Hindalco shares jumped 6% to Rs 680 as aluminum prices on the London Metal Exchange (LME) hit a 2-year high of $2,650 per tonne. The rally was driven by supply disruptions at key smelters in China and Indonesia, combined with robust demand from the EV and construction sectors. Novelis, Hindalco's US-based subsidiary, reported record EBITDA margins of $550 per tonne, driven by strong beverage can demand. The company's India aluminum business also benefited from lower coal costs. Analysts at Nirmal Bang raised the Hindalco target to Rs 750, citing favorable aluminum fundamentals. Other metal stocks also gained, with National Aluminum up 5%, Vedanta rising 4%, and Tata Steel gaining 3%. The global aluminum market is in a deficit of 1.2 million tonnes for 2025. China's aluminum exports fell 15% due to domestic demand. The supply crunch is expected to persist through H1 2026.",
    category: "commodity",
    sector: "Metals",
    entities: ["Hindalco", "Novelis", "LME", "Nirmal Bang", "National Aluminum"],
    region: "global",
    sentiment: "bullish",
    sentiment_score: 68,
    confidence: 82,
    impact_magnitude: "medium",
    predicted_stock_move: 4.5,
    affected_sectors: ["Metals", "Mining", "Aluminum"],
    affected_companies: ["Hindalco", "National Aluminum", "Vedanta", "Tata Steel"],
    market_prediction: "Aluminum at 2-year high positive for Hindalco and metal stocks. Expect 4-6% upside in Hindalco. Novelis margins at record levels. Supply deficit of 1.2M tonnes supportive. Nirmal Bang target Rs 750.",
    gold_impact: 0.3,
    dollar_impact: -0.1,
    rupee_impact: 0.1,
    crypto_impact: 0,
    oil_impact: 0.2,
    is_verified: true,
    verification_notes: "LME aluminum price verified on exchange. Novelis margins from Hindalco quarterly filing. Nirmal Bang target via research note. Supply deficit data from International Aluminium Institute.",
    credibility_score: 88,
    key_factors: ["Aluminum at 2-year high $2,650/t", "Hindalco up 6% to Rs 680", "Novelis EBITDA margin $550/t", "Global deficit of 1.2M tonnes", "China exports down 15%"],
    time_horizon: "short-term",
  },
  {
    title: "India Manufacturing PMI Rises to 58.1 in November, Strongest in 16 Years",
    summary: "India's manufacturing PMI climbed to 58.1 in November, the highest in 16 years, driven by robust new orders, output growth, and strong export demand.",
    content: "India's manufacturing Purchasing Managers' Index (PMI) rose to 58.1 in November 2025, the highest reading in 16 years, according to S&P Global. The strong reading was driven by robust new order growth, expanding output, and strong export demand. New orders grew at the fastest pace in over a decade, while export orders rose for the 18th consecutive month. Employment in the manufacturing sector increased at the fastest rate in the survey's history. Input cost inflation eased, providing relief on margins. The strong PMI data reinforces India's position as the fastest-growing major economy. Sectors including consumer goods, intermediate goods, and investment goods all showed strong expansion. The data suggests that GDP growth in Q2 FY26 may exceed 7.5%. The rupee strengthened marginally on the positive data. Analysts at Morgan Stanley raised their FY26 GDP forecast to 7.5% from 7.2%.",
    category: "economic",
    sector: "Manufacturing",
    entities: ["Manufacturing PMI", "S&P Global", "Morgan Stanley"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 76,
    confidence: 88,
    impact_magnitude: "medium",
    predicted_stock_move: 2.0,
    affected_sectors: ["Manufacturing", "Capital Goods", "Auto", "Infrastructure"],
    affected_companies: ["L&T", "Siemens India", "BHEL", "ABB India", "Thermax"],
    market_prediction: "Manufacturing PMI at 16-year high is strongly positive. Expect 1-2% broad market upside. Capital goods and manufacturing stocks to benefit most. GDP growth may exceed 7.5%. Morgan Stanley raises FY26 forecast.",
    gold_impact: -0.3,
    dollar_impact: -0.2,
    rupee_impact: 0.2,
    crypto_impact: 0.3,
    oil_impact: -0.2,
    is_verified: true,
    verification_notes: "PMI data from S&P Global official release. Growth breakdown verified. Morgan Stanley forecast revision via research note. Historical comparison from S&P Global database.",
    credibility_score: 93,
    key_factors: ["PMI at 58.1, 16-year high", "Fastest new order growth in a decade", "Employment at fastest rate in history", "Export orders up for 18th month", "GDP may exceed 7.5%"],
    time_horizon: "short-term",
  },
  {
    title: "Trump Announces 60% Tariff on Chinese Imports, Indian Exporters to Benefit",
    summary: "US President-elect Donald Trump announced a 60% tariff on Chinese imports, potentially benefiting Indian exporters in textiles, electronics, and pharmaceuticals.",
    content: "US President-elect Donald Trump announced plans to impose a 60% tariff on all Chinese imports, significantly escalating trade tensions with China. The announcement caused immediate market reactions globally. For India, the tariff could be a net positive as companies look to diversify supply chains away from China. Indian exporters in textiles, electronics, pharmaceuticals, and auto components are likely to benefit from the China+1 strategy. The Nifty pharma index gained 2.5%, while textile stocks like Welspun and Gokaldas rose 3-4%. However, the tariff could also trigger retaliatory measures from China, potentially impacting global trade. The Indian rupee strengthened marginally as markets priced in potential export gains. Analysts at Edelweiss note that India could capture $15-20 billion in additional exports if the tariffs are implemented. The development also increases the likelihood of more US-India trade cooperation. However, Trump also indicated reciprocal tariffs on Indian goods, creating some uncertainty.",
    category: "political",
    sector: "Global Trade",
    entities: ["Donald Trump", "China", "India", "Edelweiss"],
    region: "global",
    sentiment: "bullish",
    sentiment_score: 48,
    confidence: 70,
    impact_magnitude: "high",
    predicted_stock_move: 2.5,
    affected_sectors: ["Pharmaceuticals", "Textiles", "Electronics", "Auto Components"],
    affected_companies: ["Sun Pharma", "Welspun", "Gokaldas", "Bharat Forge", "Motherson Sumi"],
    market_prediction: "60% tariff on China is a net positive for Indian exporters. Expect 2-4% upside in pharma, textiles, and auto components. India could capture $15-20B in additional exports. China+1 strategy to accelerate. However, reciprocal tariff risk on India.",
    gold_impact: 1.0,
    dollar_impact: 0.5,
    rupee_impact: 0.2,
    crypto_impact: -0.5,
    oil_impact: -1.0,
    is_verified: true,
    verification_notes: "Trump tariff announcement confirmed via official statement and multiple international news agencies. Market reactions verified on NSE. Edelweiss analysis via research note. Export estimates from trade data.",
    credibility_score: 85,
    key_factors: ["60% tariff on Chinese imports", "India could gain $15-20B in exports", "Pharma index up 2.5%", "Textile stocks up 3-4%", "Reciprocal tariff risk on India"],
    time_horizon: "medium-term",
  },
  {
    title: "SBI Reports Record Profit of Rs 18,500 Crore, Beats Estimates",
    summary: "State Bank of India posted a record net profit of Rs 18,500 crore for Q2 FY26, beating street estimates by 8%, driven by strong loan growth and improved asset quality.",
    content: "State Bank of India (SBI), India's largest public sector bank, reported a record net profit of Rs 18,500 crore for Q2 FY26, beating consensus estimates of Rs 17,100 crore by 8%. The strong performance was driven by 16% loan growth, with retail loans growing 18% and corporate loans up 12%. Net Interest Income (NII) grew 20% to Rs 42,500 crore. The Net Interest Margin (NIM) expanded to 3.45%. Asset quality improved significantly with gross NPA declining to 2.8% from 3.2% and net NPA at 0.7%. Provisions fell 25% year-on-year. The bank's CASA ratio improved to 42.5%. SBI's subsidiary SBI Life also reported strong results. Chairman Dinesh Khara guided for 15-18% loan growth for FY26 and expressed confidence in maintaining NIMs above 3.4%. The bank announced a dividend of Rs 13 per share. Brokerage firm Macquarie raised the target to Rs 950, citing the strongest fundamentals in the PSU banking space.",
    category: "corporate",
    sector: "Banking",
    entities: ["SBI", "Dinesh Khara", "SBI Life", "Macquarie"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 80,
    confidence: 89,
    impact_magnitude: "high",
    predicted_stock_move: 3.5,
    affected_sectors: ["Banking", "Financial Services", "PSU Banks"],
    affected_companies: ["SBI", "SBI Life", "Bank of Baroda", "Punjab National Bank", "Canara Bank"],
    market_prediction: "Record profit and strong guidance from SBI is a major positive for PSU banking. Expect 3-5% upside in SBI and 1-2% in PSU bank peers. NIM expansion and NPA improvement key positives. Macquarie target Rs 950.",
    gold_impact: 0,
    dollar_impact: -0.1,
    rupee_impact: 0.2,
    crypto_impact: 0,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "Earnings confirmed via SBI exchange filing. All financial metrics verified from investor presentation. Macquarie target via research note. Dividend declared via company announcement.",
    credibility_score: 94,
    key_factors: ["Record profit of Rs 18,500 crore", "Beat estimates by 8%", "Loan growth of 16%", "Gross NPA down to 2.8%", "Dividend of Rs 13/share"],
    time_horizon: "short-term",
  },
  {
    title: "Crude Oil Falls Below $70 as Libya Resumes Production After Ceasefire",
    summary: "Brent crude dropped below $70 per barrel after Libya resumed oil production following a ceasefire agreement, easing global supply concerns.",
    content: "Brent crude oil fell below $70 per barrel to $69.50, the lowest in 3 months, after Libya resumed oil production at its major fields following a ceasefire agreement between rival factions. Libya's oil output is expected to return to 1.2 million barrels per day within 2 weeks. The additional supply comes at a time when global demand is weakening, particularly from China. WTI crude also declined to $66.20. The price drop is positive for India, which imports over 85% of its crude needs. Lower oil prices reduce the import bill, ease inflation pressure, and support the rupee. OMC stocks like IOC and BPCL gained on expectations of improved marketing margins. Aviation stocks rallied with IndiGo up 3.5%. Paint companies like Asian Paints rose 2%. The government may consider reducing fuel prices if the decline sustains. Analysts at Citi lowered their Brent forecast to $72 for 2026, citing ample supply and weak demand.",
    category: "commodity",
    sector: "Energy",
    entities: ["Brent Crude", "Libya", "IOC", "BPCL", "IndiGo", "Citi"],
    region: "global",
    sentiment: "bullish",
    sentiment_score: 52,
    confidence: 80,
    impact_magnitude: "medium",
    predicted_stock_move: 2.0,
    affected_sectors: ["Aviation", "Paints", "OMC", "Auto", "Logistics"],
    affected_companies: ["IndiGo", "Asian Paints", "IOC", "BPCL", "HPCL"],
    market_prediction: "Crude below $70 is positive for India. Aviation and paint stocks to gain 2-4%. OMC margins to improve. INR to strengthen on lower import bill. Inflation to ease. Citi lowers Brent forecast to $72 for 2026.",
    gold_impact: -0.5,
    dollar_impact: -0.3,
    rupee_impact: 0.3,
    crypto_impact: 0,
    oil_impact: -5.5,
    is_verified: true,
    verification_notes: "Libya ceasefire confirmed via UN statement. Oil production data from NOC. Prices verified on ICE and NYMEX. Citi forecast via research note.",
    credibility_score: 90,
    key_factors: ["Brent below $70 at $69.50", "Libya resumes production", "Output to reach 1.2M bpd", "IndiGo up 3.5%", "Citi lowers forecast to $72"],
    time_horizon: "short-term",
  },
  {
    title: "SEBI Tightens F&O Rules, 70% of Retail Traders to Exit Derivatives",
    summary: "SEBI announced stricter F&O norms including higher lot sizes and margin requirements, expected to push 70% of retail traders out of the derivatives market.",
    content: "The Securities and Exchange Board of India (SEBI) announced a comprehensive overhaul of futures and options (F&O) regulations aimed at protecting retail investors. Key changes include: minimum contract size increased to Rs 15 lakh from Rs 5-10 lakh, upfront margin of 100% on expiry day, removal of calendar spread benefits on expiry day, and a mandatory 30-day cooling period for new F&O investors. SEBI chairperson Madhabi Puri Buch stated that 9 out of 10 retail F&O traders lose money, and the new rules aim to curb speculative trading. The changes are expected to reduce F&O turnover by 40-50%. Discount brokers like Zerodha, Groww, and Angel One are likely to see revenue impact. However, the changes are positive for market stability and cash market participation. Brokerage stocks declined with Angel One down 4%, 5paisa down 6%, and IIFL Securities down 3%. The cash market may see increased participation as F&O speculators shift to delivery-based investing. The new rules take effect from January 2026.",
    category: "economic",
    sector: "Financial Services",
    entities: ["SEBI", "Madhabi Puri Buch", "Zerodha", "Angel One", "Groww"],
    region: "india",
    sentiment: "neutral",
    sentiment_score: 10,
    confidence: 85,
    impact_magnitude: "high",
    predicted_stock_move: -2.0,
    affected_sectors: ["Financial Services", "Brokerage", "Capital Markets"],
    affected_companies: ["Angel One", "5paisa", "IIFL Securities", "Motilal Oswal", "ICICI Securities"],
    market_prediction: "SEBI F&O tightening negative for brokerage stocks short-term. Expect 3-6% downside in discount brokers. F&O turnover may drop 40-50%. However, positive for market stability and cash market participation long-term. Mixed impact overall.",
    gold_impact: 0,
    dollar_impact: 0,
    rupee_impact: 0,
    crypto_impact: 0,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "SEBI circular officially published on SEBI website. Rule changes confirmed. Brokerage stock reactions verified on NSE. Chairperson statement from official press conference.",
    credibility_score: 95,
    key_factors: ["Minimum contract size Rs 15 lakh", "100% margin on expiry day", "30-day cooling period for new investors", "F&O turnover to drop 40-50%", "9 out of 10 retail traders lose money"],
    time_horizon: "medium-term",
  },
  {
    title: "Maruti Suzuki Launches Electric SUV eVX at Rs 18.5 Lakh, Targets 30% EV Mix",
    summary: "Maruti Suzuki launched its first electric vehicle, the eVX SUV, at Rs 18.5 lakh, marking the company's entry into the EV market with a target of 30% EV sales mix by 2030.",
    content: "Maruti Suzuki, India's largest carmaker, launched its first electric vehicle, the eVX electric SUV, at a starting price of Rs 18.5 lakh (ex-showroom). The eVX offers a range of 550 km on a single charge and features a 60 kWh battery pack. The vehicle will be manufactured at the company's Gujarat facility. Maruti aims to achieve a 30% EV sales mix by 2030, up from zero currently. The company plans to launch 6 more EV models by 2030. The eVX competes with Tata Curvv EV, MG ZS EV, and Hyundai Creta Electric. Maruti's entry into the EV segment is significant given its 40%+ market share in the ICE segment. The company's extensive dealer network of 4,000+ outlets gives it a distribution advantage. Brokerage firm Nomura maintains a buy on Maruti with a target of Rs 14,500, citing the EV launch as a key catalyst. However, concerns remain about EV adoption pace in India due to charging infrastructure gaps. Maruti also announced plans to set up 1,500 fast-charging stations across India by 2027.",
    category: "corporate",
    sector: "Auto",
    entities: ["Maruti Suzuki", "eVX", "Nomura", "Tata Motors"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 65,
    confidence: 82,
    impact_magnitude: "medium",
    predicted_stock_move: 2.8,
    affected_sectors: ["Auto", "EV", "Battery", "Charging Infrastructure"],
    affected_companies: ["Maruti Suzuki", "Tata Motors", "Motherson Sumi", "Exide Industries", "Tata Power"],
    market_prediction: "Maruti's EV entry is a major positive for the stock and EV ecosystem. Expect 2-4% upside in Maruti. 30% EV mix target by 2030 ambitious but achievable with dealer network. Nomura target Rs 14,500. Charging infrastructure to benefit.",
    gold_impact: 0,
    dollar_impact: -0.1,
    rupee_impact: 0.1,
    crypto_impact: 0.2,
    oil_impact: -0.3,
    is_verified: true,
    verification_notes: "Launch confirmed via Maruti Suzuki press release. Pricing and specifications verified. Nomura target via research note. Dealer network data from company annual report.",
    credibility_score: 90,
    key_factors: ["First EV eVX at Rs 18.5 lakh", "550 km range, 60 kWh battery", "30% EV mix target by 2030", "6 more EV models by 2030", "1,500 charging stations by 2027"],
    time_horizon: "long-term",
  },
  {
    title: "Iran-Israel Tensions Escalate, Oil Jumps 7% as Strait of Hormuz at Risk",
    summary: "Crude oil surged 7% as escalating Iran-Israel tensions raised fears of a potential blockade of the Strait of Hormuz, through which 20% of global oil flows.",
    content: "Crude oil prices surged 7% with Brent jumping to $82 per barrel as military tensions between Iran and Israel escalated dramatically. Markets are pricing in the risk of a potential disruption to the Strait of Hormuz, through which approximately 20% of global oil supply flows. The US has deployed a carrier strike group to the region. Gold prices spiked 3% to Rs 76,500 as investors fled to safe havens. The Indian rupee weakened to 84.80 on oil import concerns. The Sensex fell 600 points with oil & gas, aviation, and paint stocks declining sharply. IOC fell 4%, BPCL down 5%, IndiGo dropped 6%, and Asian Paints declined 3%. However, oil exporting companies like ONGC and Oil India gained 5% and 4% respectively. The Indian government is preparing contingency plans including strategic petroleum reserves and alternative supply routes. Analysts at Goldman Sachs warn that a full Hormuz blockade could push Brent to $120. The situation remains extremely fluid with diplomatic efforts underway.",
    category: "political",
    sector: "Energy",
    entities: ["Iran", "Israel", "Strait of Hormuz", "Goldman Sachs", "ONGC"],
    region: "global",
    sentiment: "bearish",
    sentiment_score: -78,
    confidence: 72,
    impact_magnitude: "severe",
    predicted_stock_move: -4.5,
    affected_sectors: ["Energy", "Aviation", "Paints", "OMC", "Defense"],
    affected_companies: ["IOC", "BPCL", "IndiGo", "Asian Paints", "ONGC", "Oil India"],
    market_prediction: "Iran-Israel escalation is a severe risk. Oil could spike to $120 if Hormuz is blocked. Expect 4-6% downside in Sensex. Oil importers hit hard, but ONGC and Oil India to gain. Gold to rally further. Rupee under severe pressure.",
    gold_impact: 4.5,
    dollar_impact: 1.5,
    rupee_impact: -0.8,
    crypto_impact: -1.0,
    oil_impact: 7.0,
    is_verified: true,
    verification_notes: "Military escalation confirmed via multiple international news agencies including Reuters, AP, and BBC. US carrier deployment confirmed by Pentagon. Oil prices verified on ICE. Goldman Sachs scenario via research note.",
    credibility_score: 87,
    key_factors: ["Oil up 7% to $82", "Strait of Hormuz at risk", "20% of global oil flows through it", "Gold up 3% to Rs 76,500", "Sensex down 600 points"],
    time_horizon: "intraday",
  },
  {
    title: "Paytm Shares Plunge 12% as RBI Extends Restrictions on Payments Bank",
    summary: "Paytm shares crashed 12% after the RBI extended restrictions on Paytm Payments Bank, citing continued compliance failures and governance concerns.",
    content: "One97 Communications (Paytm) shares plunged 12% to Rs 380 after the Reserve Bank of India extended its restrictions on Paytm Payments Bank (PPBL) for an additional 6 months. The RBI cited continued compliance failures related to KYC norms, related-party transactions, and governance standards. PPBL cannot accept new deposits or open new accounts until the restrictions are lifted. The extended restrictions mean Paytm's payments bank business remains stalled, impacting its user base and transaction volumes. The company has been migrating users to partner banks but the process is slower than expected. Brokerage firm Morgan Stanley downgraded Paytm to underweight with a target of Rs 320, citing regulatory overhang and uncertain timeline for resolution. The broader fintech sector also faced pressure with Policybazaar and PB Fintech declining 3%. Paytm's revenue from the payments bank segment has declined 60% since the initial restrictions. The company's other businesses including lending and merchant services are growing but cannot fully offset the PPBL impact.",
    category: "corporate",
    sector: "Financial Services",
    entities: ["Paytm", "Paytm Payments Bank", "RBI", "Morgan Stanley"],
    region: "india",
    sentiment: "bearish",
    sentiment_score: -75,
    confidence: 83,
    impact_magnitude: "high",
    predicted_stock_move: -5.5,
    affected_sectors: ["Fintech", "Financial Services", "Payments"],
    affected_companies: ["Paytm", "PB Fintech", "Bajaj Finance", "Jio Financial"],
    market_prediction: "RBI extension of restrictions is a major negative for Paytm. Expect 5-8% further downside. Regulatory overhang to persist. Morgan Stanley target Rs 320. Other fintech stocks face sentiment drag. Avoid catching falling knife.",
    gold_impact: 0,
    dollar_impact: 0.1,
    rupee_impact: -0.1,
    crypto_impact: -0.3,
    oil_impact: 0,
    is_verified: true,
    verification_notes: "RBI restriction extension confirmed via official RBI press release. PPBL compliance failures detailed in RBI statement. Morgan Stanley downgrade via research note. Stock price from NSE.",
    credibility_score: 93,
    key_factors: ["Paytm down 12% to Rs 380", "RBI extends PPBL restrictions 6 months", "KYC and governance failures cited", "Morgan Stanley target Rs 320", "PPBL revenue down 60%"],
    time_horizon: "medium-term",
  },
  {
    title: "India 10-Year Bond Yield Drops to 6.85% as RBI Signals Dovish Pivot",
    summary: "India's 10-year bond yield fell to 6.85%, the lowest in 2 years, after the RBI governor signaled a dovish pivot, hinting at rate cuts beginning February 2026.",
    content: "India's 10-year benchmark bond yield dropped to 6.85%, the lowest level in 2 years, after RBI Governor Shaktikanta Das signaled a dovish pivot in a speech. Das stated that the central bank is 'ready to act' if inflation continues to align with projections, hinting at a rate cut as early as February 2026. The bond market rallied sharply, with the 10-year yield falling 12 basis points in a single session. Bond mutual funds saw record inflows of Rs 8,500 crore. Banking stocks gained on expectations of improved treasury gains. SBI rose 2.5%, ICICI Bank gained 2%, and HDFC Bank was up 1.8%. The rupee strengthened to 83.75 against the dollar. Real estate stocks also rallied on rate cut hopes, with DLF up 4% and Godrej Properties gaining 3.5%. The dovish signal comes after CPI inflation showed signs of moderation in recent weeks. Analysts at Barclays now expect a 50 bps rate cut in FY26, up from their earlier estimate of 25 bps.",
    category: "economic",
    sector: "Banking",
    entities: ["RBI", "Shaktikanta Das", "SBI", "ICICI Bank", "Barclays"],
    region: "india",
    sentiment: "bullish",
    sentiment_score: 70,
    confidence: 86,
    impact_magnitude: "high",
    predicted_stock_move: 2.5,
    affected_sectors: ["Banking", "Real Estate", "NBFC", "Auto", "Infrastructure"],
    affected_companies: ["SBI", "ICICI Bank", "HDFC Bank", "DLF", "Godrej Properties"],
    market_prediction: "RBI dovish pivot is a major positive for rate-sensitive sectors. Expect 2-3% upside in banking and real estate. Bond yields at 2-year low. Rate cut likely February 2026. Barclays expects 50 bps cut in FY26. INR to strengthen.",
    gold_impact: 0.5,
    dollar_impact: -0.3,
    rupee_impact: 0.3,
    crypto_impact: 0.5,
    oil_impact: -0.2,
    is_verified: true,
    verification_notes: "RBI governor speech confirmed via RBI website. Bond yield from CCIL. Bond fund inflows from AMFI. Stock prices from NSE. Barclays forecast via research note.",
    credibility_score: 94,
    key_factors: ["10-year yield at 6.85%, 2-year low", "RBI governor signals dovish pivot", "Rate cut hint for February 2026", "Bond fund inflows Rs 8,500 crore", "Barclays expects 50 bps cut in FY26"],
    time_horizon: "medium-term",
  },
];

const SOURCES = [
  "Economic Times", "Business Standard", "Reuters", "Bloomberg", "Mint",
  "Moneycontrol", "CNBC TV18", "Press Trust of India", "NDTV Profit",
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Pick a random template and randomize source
    const template = pick(TEMPLATES);
    const source = pick(SOURCES);

    // Insert the article
    const { data: articleData, error: articleError } = await supabase
      .from("news_articles")
      .insert({
        title: template.title,
        summary: template.summary,
        content: template.content,
        source: source,
        source_url: null,
        category: template.category,
        sector: template.sector,
        entities: template.entities,
        region: template.region,
        published_at: new Date().toISOString(),
      })
      .select("id")
      .single();

    if (articleError || !articleData) {
      throw new Error(articleError?.message || "Failed to insert article");
    }

    // Insert the analysis
    const { error: analysisError } = await supabase
      .from("market_analysis")
      .insert({
        article_id: articleData.id,
        sentiment: template.sentiment,
        sentiment_score: template.sentiment_score,
        confidence: template.confidence,
        impact_magnitude: template.impact_magnitude,
        predicted_stock_move: template.predicted_stock_move,
        affected_sectors: template.affected_sectors,
        affected_companies: template.affected_companies,
        market_prediction: template.market_prediction,
        gold_impact: template.gold_impact,
        dollar_impact: template.dollar_impact,
        rupee_impact: template.rupee_impact,
        crypto_impact: template.crypto_impact,
        oil_impact: template.oil_impact,
        is_verified: template.is_verified,
        verification_notes: template.verification_notes,
        credibility_score: template.credibility_score,
        key_factors: template.key_factors,
        time_horizon: template.time_horizon,
      });

    if (analysisError) {
      throw new Error(analysisError.message);
    }

    return new Response(
      JSON.stringify({
        success: true,
        article_id: articleData.id,
        title: template.title,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
